import { Lecture } from '../types';

export const SAMPLE_LECTURES: Lecture[] = [
  // 1. OPERATING SYSTEMS: DEADLOCKS
  {
    id: 'sample_os_deadlocks',
    title: 'Operating Systems: Deadlock Characterization & Prevention',
    courseSubject: 'Computer Science & Engineering · CS304',
    createdAt: Date.now() - 86400000 * 2, // 2 days ago
    durationSeconds: 2740, // 45m 40s
    language: 'en',
    isSample: true,
    telemetry: {
      modelName: 'Whisper Tiny (ONNX WebGPU)',
      backendUsed: 'webgpu',
      audioDurationSeconds: 2740,
      transcriptionTimeMs: 142000,
      realTimeFactor: 0.05,
      chunksCount: 92,
      geminiRequestsCount: 1,
      measuredAt: Date.now() - 86400000 * 2,
    },
    topics: [
      {
        id: 'top_os_1',
        title: 'Introduction to System Resources & Deadlock Definition',
        startTimestamp: '00:00',
        endTimestamp: '08:15',
        summary: 'Definition of a deadlock state where every process in a set is waiting for an event that only another process in the set can cause.',
      },
      {
        id: 'top_os_2',
        title: 'The Four Necessary Coffman Conditions',
        startTimestamp: '08:16',
        endTimestamp: '18:30',
        summary: 'Detailed derivation of Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait conditions.',
      },
      {
        id: 'top_os_3',
        title: 'Resource Allocation Graph (RAG) Analysis',
        startTimestamp: '18:31',
        endTimestamp: '28:45',
        summary: 'Graph theoretic model: request edges, assignment edges, cycles, and single vs multiple instance resource types.',
      },
      {
        id: 'top_os_4',
        title: 'Deadlock Handling Strategies & Prevention Protocols',
        startTimestamp: '28:46',
        endTimestamp: '37:10',
        summary: 'Invalidating Coffman conditions systematically: linear resource ordering to prevent circular wait.',
      },
      {
        id: 'top_os_5',
        title: "Banker's Algorithm & Safe State Verification",
        startTimestamp: '37:11',
        endTimestamp: '45:40',
        summary: "Dijkstra's Banker's algorithm data structures: Allocation, Max, Available, and Need matrices with safety checks.",
      },
    ],
    summary: {
      tldr: 'A comprehensive study of deadlock characterization, the four necessary Coffman conditions, Resource Allocation Graphs (RAG), and prevention methodologies including linear resource numbering and Banker\'s safe state algorithms.',
      keyPoints: [
        {
          point: 'Deadlock Definition',
          explanation: 'A set of processes is deadlocked when every process in the set is waiting for a resource that is allocated to another waiting process in the same set.',
          evidenceTimestamp: '02:15',
        },
        {
          point: 'The Four Coffman Conditions are simultaneously necessary',
          explanation: 'Mutual exclusion, Hold and wait, No preemption, and Circular wait must all hold concurrently for a deadlock to arise in an operating system.',
          evidenceTimestamp: '09:40',
        },
        {
          point: 'A cycle in RAG is necessary but not always sufficient',
          explanation: 'If each resource type has exactly one instance, a cycle implies a deadlock. However, if resources have multiple instances, a cycle does not guarantee a deadlock.',
          evidenceTimestamp: '21:10',
        },
        {
          point: 'Circular Wait Elimination via Linear Ordering',
          explanation: 'Imposing a strict total ordering F: R -> N on all resource types and requiring processes to request resources only in increasing order guarantees absence of circular wait.',
          evidenceTimestamp: '32:14',
        },
        {
          point: 'Safe State vs Unsafe State in Deadlock Avoidance',
          explanation: 'An unsafe state is not necessarily a deadlock, but every deadlocked state is an unsafe state. The Banker\'s algorithm prevents transitions into unsafe states.',
          evidenceTimestamp: '41:20',
        },
      ],
      formulas: [
        {
          name: 'Need Matrix Equation',
          formula: 'Need[i, j] = Max[i, j] - Allocation[i, j]',
          description: 'Defines the remaining resource instances of type j that process i may request before completing execution.',
          evidenceTimestamp: '39:15',
        },
        {
          name: 'Safety Condition Vector Inequality',
          formula: 'Need_i <= Work',
          description: 'Checks whether the remaining available resources (Work) can satisfy the maximum pending need of process i.',
          evidenceTimestamp: '42:05',
        },
        {
          name: 'Resource Request Grant Rule',
          formula: 'Request_i <= Need_i AND Request_i <= Available',
          description: 'A process request can only be considered if it does not exceed its declared maximum need and the physical inventory available.',
          evidenceTimestamp: '44:12',
        },
      ],
      definitions: [
        {
          term: 'Deadlock',
          definition: 'A permanent blocking state where a group of processes are unable to proceed because each process is holding a resource and waiting for another resource held by someone else in the group.',
          evidenceTimestamp: '03:10',
        },
        {
          term: 'Mutual Exclusion',
          definition: 'At least one resource must be held in a non-shareable mode; only one process at a time can use the resource.',
          evidenceTimestamp: '10:15',
        },
        {
          term: 'Hold and Wait',
          definition: 'A process must be currently holding at least one resource and waiting to acquire additional resources that are currently being held by other processes.',
          evidenceTimestamp: '12:20',
        },
        {
          term: 'No Preemption',
          definition: 'Resources cannot be forcefully seized from a process; a resource can be released only voluntarily by the process holding it after task completion.',
          evidenceTimestamp: '14:50',
        },
        {
          term: 'Circular Wait',
          definition: 'A closed chain of processes {P0, P1, ..., Pn} exists such that P0 waits for a resource held by P1, P1 waits for P2, and Pn waits for P0.',
          evidenceTimestamp: '32:14',
        },
        {
          term: 'Safe Sequence',
          definition: 'A sequence of processes <P1, P2, ..., Pn> such that for each Pi, the resources that Pi can still request can be satisfied by currently available resources plus resources held by all Pj with j < i.',
          evidenceTimestamp: '40:30',
        },
      ],
      importantConcepts: [
        {
          concept: 'Havender\'s Linear Ordering Protocol',
          details: 'Assign each resource a unique integer rank. If process holds resource R_i, it can only request R_j if rank(R_j) > rank(R_i). This mathematically breaks circular dependencies.',
          prerequisites: 'Graph Theory & Directed Acyclic Graphs',
          evidenceTimestamp: '34:25',
        },
        {
          concept: 'Banker\'s Algorithm Work Vector Updates',
          details: 'When process Pi completes, Work = Work + Allocation_i. This simulates resource reclamation in polynomial time O(m * n^2).',
          prerequisites: 'Matrix arithmetic and state-space search',
          evidenceTimestamp: '43:10',
        },
      ],
    },
    flashcards: [
      {
        id: 'fc_os_1',
        question: 'What are the four necessary Coffman conditions for a deadlock to occur?',
        answer: '1. Mutual Exclusion, 2. Hold and Wait, 3. No Preemption, and 4. Circular Wait.',
        sourceTimestamp: '09:40',
        difficulty: 'easy',
      },
      {
        id: 'fc_os_2',
        question: 'Does a cycle in a Resource Allocation Graph always imply a deadlock?',
        answer: 'No. A cycle implies a deadlock ONLY if all resource types in the cycle have a single instance. With multiple instances per resource type, a cycle is necessary but not sufficient.',
        sourceTimestamp: '21:10',
        difficulty: 'medium',
      },
      {
        id: 'fc_os_3',
        question: 'How does Havender\'s protocol prevent Circular Wait?',
        answer: 'By establishing a global total ordering on all resources: a process can only request resources with an integer rank strictly greater than any resource it currently holds.',
        sourceTimestamp: '32:14',
        difficulty: 'medium',
      },
      {
        id: 'fc_os_4',
        question: 'What is the relationship between safe states and deadlocks?',
        answer: 'Deadlocks are a strict subset of unsafe states. All safe states are deadlock-free, but an unsafe state does not guarantee an immediate deadlock.',
        sourceTimestamp: '41:20',
        difficulty: 'easy',
      },
      {
        id: 'fc_os_5',
        question: 'How is the Need matrix calculated in the Banker\'s Algorithm?',
        answer: 'Need[i, j] = Max[i, j] - Allocation[i, j].',
        sourceTimestamp: '39:15',
        difficulty: 'easy',
      },
      {
        id: 'fc_os_6',
        question: 'What is the primary drawback of eliminating the Hold and Wait condition by requiring all resources upfront?',
        answer: 'Severe resource under-utilization (resources remain idle for long periods) and potential starvation of processes requiring multiple popular resources.',
        sourceTimestamp: '30:45',
        difficulty: 'medium',
      },
      {
        id: 'fc_os_7',
        question: 'In a Resource Allocation Graph, what does a directed edge from Resource R_j to Process P_i represent?',
        answer: 'An Assignment Edge (the resource instance has been granted to and is currently held by Process P_i).',
        sourceTimestamp: '19:40',
        difficulty: 'easy',
      },
      {
        id: 'fc_os_8',
        question: 'What time complexity does the Banker\'s Safety Algorithm operate under with n processes and m resource types?',
        answer: 'O(m * n^2) operations.',
        sourceTimestamp: '43:50',
        difficulty: 'hard',
      },
      {
        id: 'fc_os_9',
        question: 'How can the No Preemption condition be broken to prevent deadlocks?',
        answer: 'If a process holding resources requests another resource that cannot be immediately allocated, all of its currently held resources are preempted and placed on the wait queue.',
        sourceTimestamp: '31:25',
        difficulty: 'medium',
      },
      {
        id: 'fc_os_10',
        question: 'Why is deadlock detection and recovery rarely used in general-purpose desktop operating systems?',
        answer: 'The computational overhead of periodic cycle checks and the severe cost of aborting processes or rolling back transactions (often handled via the Ostrich algorithm).',
        sourceTimestamp: '45:10',
        difficulty: 'hard',
      },
    ],
    quiz: [
      {
        id: 'qz_os_1',
        question: 'Which of the following conditions is violated when resources can be shared simultaneously by multiple processes?',
        options: ['Hold and Wait', 'Mutual Exclusion', 'No Preemption', 'Circular Wait'],
        correctAnswer: 'Mutual Exclusion',
        explanation: 'Mutual exclusion requires non-shareable resource access. Read-only files can be shared concurrently, violating mutual exclusion and preventing deadlocks.',
        sourceTimestamp: '10:15',
      },
      {
        id: 'qz_os_2',
        question: 'In a system with multiple instances per resource type, the presence of a cycle in the Resource Allocation Graph signifies:',
        options: [
          'A definite deadlock state',
          'A potential deadlock, requiring knot or safety matrix evaluation',
          'No deadlock is possible',
          'System is in a safe sequence',
        ],
        correctAnswer: 'A potential deadlock, requiring knot or safety matrix evaluation',
        explanation: 'For multiple instance resources, a cycle is a necessary condition for deadlock, but not a sufficient condition. Other processes outside the cycle could release instances.',
        sourceTimestamp: '21:10',
      },
      {
        id: 'qz_os_3',
        question: 'Why does circular wait occur in concurrent systems?',
        options: [
          'Processes release resources prematurely',
          'A closed loop of dependency exists where P_i waits for resource held by P_{i+1} and P_n waits for P_0',
          'CPU scheduling operates in Round Robin mode',
          'Process priority inversion triggers interrupt handling',
        ],
        correctAnswer: 'A closed loop of dependency exists where P_i waits for resource held by P_{i+1} and P_n waits for P_0',
        explanation: 'Circular wait is explicitly the closed chain of waiting relationships where no process can proceed without the resource held by the successor in the loop.',
        sourceTimestamp: '32:14',
      },
      {
        id: 'qz_os_4',
        question: 'To eliminate circular wait via resource hierarchy, what rule must be enforced on resource requests?',
        options: [
          'Request resources in decreasing order of process ID',
          'Request all resources strictly in monotonically increasing order of global resource ranks',
          'Allow request only when holding zero resources',
          'Preempt resources every 10 milliseconds',
        ],
        correctAnswer: 'Request all resources strictly in monotonically increasing order of global resource ranks',
        explanation: 'Havender proved that if all resources are allocated in an increasing order of their assigned integer indices, a directed cycle in resource allocation cannot form.',
        sourceTimestamp: '33:40',
      },
      {
        id: 'qz_os_5',
        question: 'Given Max = [7, 5, 3] and Allocation = [3, 2, 2], what is the Need vector for this process?',
        options: ['[4, 3, 1]', '[10, 7, 5]', '[4, 3, 5]', '[2, 1, 1]'],
        correctAnswer: '[4, 3, 1]',
        explanation: 'Need = Max - Allocation = [7-3, 5-2, 3-2] = [4, 3, 1].',
        sourceTimestamp: '39:15',
      },
      {
        id: 'qz_os_6',
        question: 'Which statement accurately describes an unsafe state in deadlock avoidance?',
        options: [
          'An unsafe state is synonymous with a deadlocked state',
          'An unsafe state cannot transition back to a safe state',
          'An unsafe state is not necessarily deadlocked, but may lead to deadlock if worst-case resource requests occur',
          'Unsafe states can only happen in single-threaded systems',
        ],
        correctAnswer: 'An unsafe state is not necessarily deadlocked, but may lead to deadlock if worst-case resource requests occur',
        explanation: 'Safety is a guarantee: in a safe state, the OS can avoid deadlock under maximum claims. In an unsafe state, deadlock is not guaranteed unless processes actually demand their maximum declared need.',
        sourceTimestamp: '41:20',
      },
      {
        id: 'qz_os_7',
        question: 'What is the algorithmic time complexity of verifying a safe sequence in Banker\'s Algorithm?',
        options: ['O(n + m)', 'O(m * n)', 'O(m * n^2)', 'O(2^n)'],
        correctAnswer: 'O(m * n^2)',
        explanation: 'In the worst case, the algorithm iterates n times through the remaining processes, and for each candidate process compares m resource elements: n * n * m = O(m * n^2).',
        sourceTimestamp: '43:50',
      },
      {
        id: 'qz_os_8',
        question: 'Which deadlock handling strategy is officially nicknamed the "Ostrich Algorithm"?',
        options: [
          'Deadlock Avoidance via dynamic state simulation',
          'Deadlock Prevention via protocol restrictions',
          'Ignoring the problem altogether assuming deadlocks are sufficiently rare',
          'Periodic checkpointing and rollback',
        ],
        correctAnswer: 'Ignoring the problem altogether assuming deadlocks are sufficiently rare',
        explanation: 'The Ostrich approach sticks its head in the sand: it ignores deadlocks because prevention and detection overhead costs more than occasional manual user restart.',
        sourceTimestamp: '45:10',
      },
    ],
    groundedQA: [
      {
        id: 'sample_qa_os_1',
        question: 'Why does deadlock occur in this lecture?',
        answer: 'According to the lecture, a deadlock occurs because four conditions hold simultaneously: Mutual Exclusion (non-shareable resources), Hold and Wait (processes holding resources while seeking others), No Preemption (resources cannot be forcibly taken), and Circular Wait (a closed dependency loop where each process waits on the next). The professor explains that if any one of these four conditions is broken, a deadlock cannot occur.',
        confidence: 'high',
        citations: [
          {
            timestamp: '09:40',
            snippet: 'All four Coffman conditions must hold simultaneously for a deadlock to exist.',
            topic: 'The Four Necessary Coffman Conditions',
          },
          {
            timestamp: '32:14',
            snippet: 'Circular wait is the fourth condition: P0 waits for resource held by P1, up to Pn waiting for P0, completing the circle.',
            topic: 'Circular Wait Analysis',
          },
        ],
        followUpSuggestions: [
          'How can we prevent Circular Wait in practice?',
          'What is the difference between deadlock prevention and deadlock avoidance?',
        ],
        createdAt: Date.now() - 3600000,
      },
    ],
    transcript: [
      {
        id: 'os_seg_1',
        start: 0,
        end: 35,
        startTimestamp: '00:00',
        endTimestamp: '00:35',
        text: 'Good morning everyone. Today we are entering one of the most critical topics in Operating Systems engineering: Deadlock characterization, prevention, and avoidance.',
      },
      {
        id: 'os_seg_2',
        start: 35,
        end: 75,
        startTimestamp: '00:35',
        endTimestamp: '01:15',
        text: 'In any multiprogrammed system, processes compete for a finite set of resources. These resources could be physical devices like printers, magnetic tape drives, or memory blocks, or logical resources like file locks, mutex semaphores, and database rows.',
      },
      {
        id: 'os_seg_3',
        start: 75,
        end: 135,
        startTimestamp: '01:15',
        endTimestamp: '02:15',
        text: 'Under normal operation, a process utilizes a resource in three steps: Request, Use, and Release. But what happens if the requested resource is currently allocated to another process? The requesting process enters a waiting state.',
      },
      {
        id: 'os_seg_4',
        start: 135,
        end: 210,
        startTimestamp: '02:15',
        endTimestamp: '03:30',
        text: 'Here is the formal definition you must remember for your exams: A set of processes is in a deadlocked state when every process in the set is waiting for an event that can only be caused by another process in the set.',
      },
      {
        id: 'os_seg_5',
        start: 210,
        end: 300,
        startTimestamp: '03:30',
        endTimestamp: '05:00',
        text: 'Think of two trains approaching each other on the same single track. If neither train can reverse, neither can proceed. In computers, this means processes remain frozen, CPU cycles are wasted, and throughput drops to zero.',
      },
      {
        id: 'os_seg_6',
        start: 495,
        end: 580,
        startTimestamp: '08:15',
        endTimestamp: '09:40',
        text: 'In 1971, Edward G. Coffman Jr. identified four necessary conditions for deadlocks. Pay close attention: all four conditions must hold simultaneously in the system for a deadlock to arise.',
      },
      {
        id: 'os_seg_7',
        start: 580,
        end: 670,
        startTimestamp: '09:40',
        endTimestamp: '11:10',
        text: 'Condition number one is Mutual Exclusion. At least one resource must be held in a non-shareable mode. That means only one process can use the resource at any given moment. If another process requests it, it must wait until the resource is released.',
      },
      {
        id: 'os_seg_8',
        start: 670,
        end: 780,
        startTimestamp: '11:10',
        endTimestamp: '13:00',
        text: 'Condition number two: Hold and Wait. A process must be holding at least one resource and simultaneously waiting to acquire additional resources that are held by other processes.',
      },
      {
        id: 'os_seg_9',
        start: 780,
        end: 900,
        startTimestamp: '13:00',
        endTimestamp: '15:00',
        text: 'Condition three: No Preemption. Resources cannot be forcibly preempted from a process. A resource can only be released voluntarily by the holding process after it has finished its designated computation.',
      },
      {
        id: 'os_seg_10',
        start: 900,
        end: 1110,
        startTimestamp: '15:00',
        endTimestamp: '18:30',
        text: 'Condition four: Circular Wait. There exists a closed set of waiting processes {P0, P1, ..., Pn} such that P0 is waiting for a resource held by P1, P1 is waiting for P2, and Pn is waiting for a resource held by P0.',
      },
      {
        id: 'os_seg_11',
        start: 1110,
        end: 1270,
        startTimestamp: '18:30',
        endTimestamp: '21:10',
        text: 'Now let us represent this visually using a Resource Allocation Graph, or RAG. Circles represent processes, rectangles represent resource types with dots inside indicating instances. A request edge goes from Process to Resource; an assignment edge goes from Resource instance to Process.',
      },
      {
        id: 'os_seg_12',
        start: 1270,
        end: 1450,
        startTimestamp: '21:10',
        endTimestamp: '24:10',
        text: 'Here is a fundamental GATE exam question: If a resource allocation graph contains a cycle, is the system definitely in deadlock? The answer is: only if every resource type has exactly one instance. If there are multiple instances, a cycle is necessary but not sufficient!',
      },
      {
        id: 'os_seg_13',
        start: 1720,
        end: 1934,
        startTimestamp: '28:40',
        endTimestamp: '32:14',
        text: 'How do we solve deadlocks? The first method is Deadlock Prevention: we ensure that at least one of the four Coffman conditions can never hold. Can we eliminate mutual exclusion? Usually no, because hardware like printers cannot be safely shared.',
      },
      {
        id: 'os_seg_14',
        start: 1934,
        end: 2080,
        startTimestamp: '32:14',
        endTimestamp: '34:40',
        text: 'The most practical condition to invalidate is Circular Wait. This is Havender\'s protocol: we assign every resource type a unique integer index F(R). A process can request a resource Rj only if F(Rj) is strictly greater than F(Ri) for any resource Ri it currently holds. Because indices must strictly increase, a circular cycle is mathematically impossible!',
      },
      {
        id: 'os_seg_15',
        start: 2230,
        end: 2420,
        startTimestamp: '37:10',
        endTimestamp: '40:20',
        text: 'Next, let us examine Deadlock Avoidance and the famous Banker\'s Algorithm proposed by Edsger Dijkstra. Unlike prevention, avoidance allows dynamic resource allocation, but checks before every grant whether the state remains safe.',
      },
      {
        id: 'os_seg_16',
        start: 2420,
        end: 2580,
        startTimestamp: '40:20',
        endTimestamp: '43:00',
        text: 'We define the Need matrix: Need[i, j] = Max[i, j] - Allocation[i, j]. If the available resources can satisfy the pending need of process i, process i can complete, releasing all its held resources back to Available.',
      },
      {
        id: 'os_seg_17',
        start: 2580,
        end: 2740,
        startTimestamp: '43:00',
        endTimestamp: '45:40',
        text: 'If there exists a safe sequence of all processes, the system is in a safe state and deadlock is avoided. Remember: all safe states are deadlock-free, but unsafe states only mean potential deadlock. That concludes our deadlock foundations.',
      },
    ],
  },

  // 2. DBMS: NORMALIZATION
  {
    id: 'sample_dbms_normalization',
    title: 'Database Management Systems: Relational Normalization (1NF to BCNF)',
    courseSubject: 'Computer Science & Engineering · CS302',
    createdAt: Date.now() - 86400000 * 5,
    durationSeconds: 2460, // 41m 00s
    language: 'en',
    isSample: true,
    telemetry: {
      modelName: 'Whisper Tiny (ONNX WebGPU)',
      backendUsed: 'webgpu',
      audioDurationSeconds: 2460,
      transcriptionTimeMs: 128000,
      realTimeFactor: 0.052,
      chunksCount: 82,
      geminiRequestsCount: 1,
      measuredAt: Date.now() - 86400000 * 5,
    },
    topics: [
      {
        id: 'top_db_1',
        title: 'Pitfalls of Bad Relational Schema & Modification Anomalies',
        startTimestamp: '00:00',
        endTimestamp: '07:20',
        summary: 'Redundancy, Insertion anomaly, Deletion anomaly, and Update anomaly in unnormalized database relations.',
      },
      {
        id: 'top_db_2',
        title: 'Functional Dependencies & Armstrong\'s Axioms',
        startTimestamp: '07:21',
        endTimestamp: '16:40',
        summary: 'Definition of X -> Y, reflexivity, augmentation, transitivity, and finding attribute closures X+.',
      },
      {
        id: 'top_db_3',
        title: 'First (1NF) and Second Normal Form (2NF)',
        startTimestamp: '16:41',
        endTimestamp: '25:10',
        summary: 'Atomic domain constraints for 1NF; elimination of partial functional dependencies on candidate keys for 2NF.',
      },
      {
        id: 'top_db_4',
        title: 'Third Normal Form (3NF) & Transitive Dependencies',
        startTimestamp: '25:11',
        endTimestamp: '33:30',
        summary: 'Strict conditions for 3NF: for every FD X -> Y, either X is a superkey or Y is a prime attribute.',
      },
      {
        id: 'top_db_5',
        title: 'Boyce-Codd Normal Form (BCNF) & Decomposition Properties',
        startTimestamp: '33:31',
        endTimestamp: '41:00',
        summary: 'Elimination of all non-trivial dependencies where X is not a superkey; lossless-join vs dependency preservation tradeoffs.',
      },
    ],
    summary: {
      tldr: 'A systematic treatment of relational database design anomalies, functional dependencies, attribute closure computation, and progressive decomposition through 1NF, 2NF, 3NF, and Boyce-Codd Normal Form (BCNF).',
      keyPoints: [
        {
          point: 'Modification Anomalies drive the need for normalization',
          explanation: 'Poorly structured tables create insertion, deletion, and update anomalies where modifying a single attribute either corrupts data or unintentionally deletes unrelated records.',
          evidenceTimestamp: '04:12',
        },
        {
          point: 'Candidate Keys are derived via Attribute Closure X+',
          explanation: 'An attribute set X is a candidate key if its closure X+ includes all attributes of the relation and no proper subset of X has this property (minimality).',
          evidenceTimestamp: '12:30',
        },
        {
          point: '2NF removes Partial Dependencies',
          explanation: 'A relation in 1NF is in 2NF if and only if no non-prime attribute is functionally dependent on any proper subset of any candidate key.',
          evidenceTimestamp: '20:45',
        },
        {
          point: '3NF relaxes BCNF for Dependency Preservation',
          explanation: '3NF permits an FD X -> Y where X is not a superkey, provided that Y is a prime attribute. BCNF disallows this completely, sometimes sacrificing dependency preservation.',
          evidenceTimestamp: '28:10',
        },
        {
          point: 'Lossless-Join Decomposition is Mandatory',
          explanation: 'A decomposition into R1 and R2 is lossless if and only if (R1 ∩ R2) -> R1 or (R1 ∩ R2) -> R2.',
          evidenceTimestamp: '36:40',
        },
      ],
      formulas: [
        {
          name: 'Lossless-Join Theorem',
          formula: '(R1 ∩ R2) -> R1 OR (R1 ∩ R2) -> R2',
          description: 'The common attributes of the two decomposed relations must form a superkey of at least one of the relations.',
          evidenceTimestamp: '36:40',
        },
        {
          name: 'Functional Dependency Definition',
          formula: '∀ t1, t2 ∈ r: t1[X] = t2[X] ⇒ t1[Y] = t2[Y]',
          description: 'If two tuples agree on attribute set X, they must also agree on attribute set Y.',
          evidenceTimestamp: '08:50',
        },
      ],
      definitions: [
        {
          term: 'Functional Dependency (X -> Y)',
          definition: 'A constraint between two sets of attributes in a relation, specifying that the value of X uniquely determines the value of Y.',
          evidenceTimestamp: '08:50',
        },
        {
          term: 'Prime Attribute',
          definition: 'An attribute that is a member of at least one candidate key for the relation schema.',
          evidenceTimestamp: '18:15',
        },
        {
          term: 'Partial Dependency',
          definition: 'A functional dependency where a non-prime attribute depends on a proper subset of a composite candidate key.',
          evidenceTimestamp: '21:05',
        },
        {
          term: 'Transitive Dependency',
          definition: 'A functional dependency X -> Z that is derived through an intermediate set Y, such that X -> Y and Y -> Z where Y is not a candidate key.',
          evidenceTimestamp: '26:30',
        },
      ],
    },
    flashcards: [
      {
        id: 'fc_db_1',
        question: 'What is an Insertion Anomaly in relational databases?',
        answer: 'The inability to insert valid data about an independent entity without simultaneously supplying data for an unrelated entity (e.g. adding a student without course enrollment).',
        sourceTimestamp: '04:12',
        difficulty: 'easy',
      },
      {
        id: 'fc_db_2',
        question: 'What distinguishes a Superkey from a Candidate Key?',
        answer: 'A superkey uniquely identifies every tuple in the relation. A candidate key is a minimal superkey containing no extraneous attributes.',
        sourceTimestamp: '11:45',
        difficulty: 'easy',
      },
      {
        id: 'fc_db_3',
        question: 'When is a relation in 1NF violated?',
        answer: 'When an attribute contains non-atomic, composite, or multivalued values (such as an array or comma-separated phone numbers in a single column).',
        sourceTimestamp: '17:20',
        difficulty: 'easy',
      },
      {
        id: 'fc_db_4',
        question: 'What condition must hold for a relation in 1NF to also satisfy 2NF?',
        answer: 'It must contain no partial dependencies: every non-prime attribute must be fully functionally dependent on every candidate key.',
        sourceTimestamp: '20:45',
        difficulty: 'medium',
      },
      {
        id: 'fc_db_5',
        question: 'What are the two acceptable conditions for every non-trivial FD X -> Y in 3NF?',
        answer: 'Either X is a superkey of the relation, OR Y is a prime attribute (part of some candidate key).',
        sourceTimestamp: '28:10',
        difficulty: 'medium',
      },
      {
        id: 'fc_db_6',
        question: 'How does BCNF differ strictly from 3NF?',
        answer: 'In BCNF, for every non-trivial FD X -> Y, X MUST be a superkey. BCNF eliminates the exemption where Y is a prime attribute.',
        sourceTimestamp: '34:15',
        difficulty: 'medium',
      },
      {
        id: 'fc_db_7',
        question: 'Can every relation schema always be decomposed into BCNF while preserving all functional dependencies?',
        answer: 'No. While a lossless-join BCNF decomposition is always achievable, dependency preservation is not guaranteed. 3NF guarantees both.',
        sourceTimestamp: '38:50',
        difficulty: 'hard',
      },
      {
        id: 'fc_db_8',
        question: 'What are the three primary Armstrong Axioms for functional dependencies?',
        answer: 'Reflexivity (if Y ⊆ X, then X -> Y), Augmentation (if X -> Y, then XZ -> YZ), and Transitivity (if X -> Y and Y -> Z, then X -> Z).',
        sourceTimestamp: '14:10',
        difficulty: 'medium',
      },
      {
        id: 'fc_db_9',
        question: 'What is the necessary and sufficient condition for a decomposition into R1 and R2 to be lossless?',
        answer: '(R1 ∩ R2) -> R1 or (R1 ∩ R2) -> R2 (their intersection must be a superkey of at least one of the decomposed schemas).',
        sourceTimestamp: '36:40',
        difficulty: 'medium',
      },
      {
        id: 'fc_db_10',
        question: 'What is an update anomaly?',
        answer: 'A situation where data redundancy requires updating multiple rows for a single real-world fact; failing to update all rows results in inconsistent data.',
        sourceTimestamp: '06:05',
        difficulty: 'easy',
      },
    ],
    quiz: [
      {
        id: 'qz_db_1',
        question: 'A table with attributes (StudentID, CourseID, StudentName, Grade) has primary key (StudentID, CourseID). Which dependency causes a 2NF violation?',
        options: [
          '(StudentID, CourseID) -> Grade',
          'StudentID -> StudentName',
          'CourseID -> Grade',
          'Grade -> StudentID',
        ],
        correctAnswer: 'StudentID -> StudentName',
        explanation: 'StudentName is a non-prime attribute dependent on StudentID, which is a proper subset of the composite candidate key (StudentID, CourseID). This is a partial dependency.',
        sourceTimestamp: '21:05',
      },
      {
        id: 'qz_db_2',
        question: 'For a functional dependency X -> Y, in which normal form is Y allowed to be a prime attribute when X is not a superkey?',
        options: ['1NF only', '2NF only', '3NF', 'BCNF'],
        correctAnswer: '3NF',
        explanation: '3NF explicitly allows X -> Y if Y is a prime attribute, even if X is not a superkey. BCNF prohibits this entirely.',
        sourceTimestamp: '28:10',
      },
      {
        id: 'qz_db_3',
        question: 'Which decomposition property ensures that rejoining decomposed tables produces the exact original records without spurious tuples?',
        options: ['Dependency preservation', 'Lossless-join', 'Minimal cover', 'Denormalization'],
        correctAnswer: 'Lossless-join',
        explanation: 'Lossless-join decomposition guarantees that R1 ⨝ R2 = R with no phantom or spurious records generated during the natural join.',
        sourceTimestamp: '36:40',
      },
      {
        id: 'qz_db_4',
        question: 'If R(A, B, C, D) has FDs {A -> B, B -> C, C -> D}, what is the attribute closure A+?',
        options: ['{A, B}', '{A, B, C}', '{A, B, C, D}', '{A}'],
        correctAnswer: '{A, B, C, D}',
        explanation: 'Starting with A: A -> B adds B; B -> C adds C; C -> D adds D. Hence A+ = {A, B, C, D}, making A a candidate key.',
        sourceTimestamp: '13:10',
      },
      {
        id: 'qz_db_5',
        question: 'What is always guaranteed when decomposing into 3NF that is NOT guaranteed for BCNF?',
        options: ['No redundancy', 'Dependency preservation', 'Lossless-join', 'Atomic attribute values'],
        correctAnswer: 'Dependency preservation',
        explanation: 'It is a foundational DBMS theorem that 3NF decomposition can always achieve both lossless-join and dependency preservation simultaneously, while BCNF may sacrifice dependency preservation.',
        sourceTimestamp: '38:50',
      },
      {
        id: 'qz_db_6',
        question: 'Which Armstrong inference rule states: "If X -> Y and Y -> Z, then X -> Z"?',
        options: ['Augmentation', 'Pseudotransitivity', 'Transitivity', 'Decomposition'],
        correctAnswer: 'Transitivity',
        explanation: 'The Transitivity axiom establishes that functional determination propagates transitively through intermediate attribute sets.',
        sourceTimestamp: '14:10',
      },
      {
        id: 'qz_db_7',
        question: 'Which normal form addresses anomalies arising specifically from multivalued dependencies (MVDs)?',
        options: ['2NF', '3NF', 'BCNF', '4NF'],
        correctAnswer: '4NF',
        explanation: 'Fourth Normal Form (4NF) eliminates non-trivial multivalued dependencies (X ↠ Y) that cannot be constrained by functional dependencies alone.',
        sourceTimestamp: '40:15',
      },
      {
        id: 'qz_db_8',
        question: 'What is a deletion anomaly?',
        options: [
          'Accidental deletion of unrelated entities due to shared tuples in denormalized designs',
          'Database disk full error during DROP TABLE',
          'Foreign key cascade failures in normalized tables',
          'Concurrency deadlock between transactions',
        ],
        correctAnswer: 'Accidental deletion of unrelated entities due to shared tuples in denormalized designs',
        explanation: 'If student and department info are co-located in one row, deleting the last student enrolled in that department inadvertently erases the entire department\'s existence.',
        sourceTimestamp: '05:30',
      },
    ],
    groundedQA: [
      {
        id: 'sample_qa_db_1',
        question: 'Why do we need 3NF if 2NF already removes partial dependencies?',
        answer: '2NF only ensures that non-prime attributes do not depend on parts of candidate keys. However, 2NF still permits transitive dependencies where a non-prime attribute determines another non-prime attribute (for example: StudentID -> Department -> DepartmentHOD). In this scenario, updating the HOD requires updating every student row, causing update anomalies. 3NF eliminates these transitive dependencies.',
        confidence: 'high',
        citations: [
          {
            timestamp: '25:11',
            snippet: 'While 2NF eliminates partial dependencies, it leaves relations vulnerable to transitive dependencies among non-key attributes.',
            topic: 'Third Normal Form (3NF) & Transitive Dependencies',
          },
        ],
        createdAt: Date.now() - 3600000,
      },
    ],
    transcript: [
      {
        id: 'db_seg_1',
        start: 0,
        end: 45,
        startTimestamp: '00:00',
        endTimestamp: '00:45',
        text: 'Welcome back class. Today we discuss Relational Database Normalization: why we need it, how functional dependencies dictate schema design, and how to decompose tables from 1NF all the way to Boyce-Codd Normal Form.',
      },
      {
        id: 'db_seg_2',
        start: 45,
        end: 110,
        startTimestamp: '00:45',
        endTimestamp: '01:50',
        text: 'When engineers design database tables without normalization, they frequently lump multiple concepts into a single massive relation. This creates massive data redundancy, where the same fact is stored hundreds of times.',
      },
      {
        id: 'db_seg_3',
        start: 110,
        end: 252,
        startTimestamp: '01:50',
        endTimestamp: '04:12',
        text: 'This redundancy causes three destructive modification anomalies: Insertion anomalies, Deletion anomalies, and Update anomalies. For instance, an insertion anomaly occurs when you cannot register a new faculty member because they have not yet been assigned to teach a course.',
      },
      {
        id: 'db_seg_4',
        start: 252,
        end: 440,
        startTimestamp: '04:12',
        endTimestamp: '07:20',
        text: 'A deletion anomaly happens if deleting the last student enrolled in a course inadvertently deletes the entire course record from the database. An update anomaly occurs when changing a department head requires updating 5,000 student rows.',
      },
      {
        id: 'db_seg_5',
        start: 440,
        end: 590,
        startTimestamp: '07:20',
        endTimestamp: '09:50',
        text: 'To solve this mathematically, Edgar F. Codd introduced the concept of Functional Dependencies. An FD, written X -> Y, means attribute set X uniquely determines attribute set Y. If two rows agree on X, they must agree on Y.',
      },
      {
        id: 'db_seg_6',
        start: 590,
        end: 750,
        startTimestamp: '09:50',
        endTimestamp: '12:30',
        text: 'From a set of functional dependencies F, we compute attribute closures X+. The closure is the complete set of all attributes that can be functionally derived from X. If X+ equals the entire relation R, then X is a superkey!',
      },
      {
        id: 'db_seg_7',
        start: 1000,
        end: 1245,
        startTimestamp: '16:40',
        endTimestamp: '20:45',
        text: 'First Normal Form requires that every attribute domain consists of atomic, indivisible values. No arrays, no nested tables. Second Normal Form requires that the table is in 1NF and contains no partial dependencies on any candidate key.',
      },
      {
        id: 'db_seg_8',
        start: 1510,
        end: 1720,
        startTimestamp: '25:10',
        endTimestamp: '28:40',
        text: 'Third Normal Form removes transitive dependencies. For every non-trivial dependency X -> Y, either X is a superkey, or Y is a prime attribute. Prime attribute means it is part of some candidate key.',
      },
      {
        id: 'db_seg_9',
        start: 2010,
        end: 2200,
        startTimestamp: '33:30',
        endTimestamp: '36:40',
        text: 'BCNF is stricter: for every non-trivial X -> Y, X must be a superkey with no exceptions. Notice that when we decompose into BCNF, we always enforce lossless-join: (R1 ∩ R2) must determine R1 or R2. That is the core of relational normalization.',
      },
    ],
  },

  // 3. ENGINEERING MATHEMATICS: LAPLACE TRANSFORM
  {
    id: 'sample_math_laplace',
    title: 'Engineering Mathematics: Laplace Transforms & Differential Equations',
    courseSubject: 'Mathematics & Signal Processing · MA201',
    createdAt: Date.now() - 86400000 * 7,
    durationSeconds: 2880, // 48m 00s
    language: 'en',
    isSample: true,
    telemetry: {
      modelName: 'Whisper Tiny (ONNX WebGPU)',
      backendUsed: 'webgpu',
      audioDurationSeconds: 2880,
      transcriptionTimeMs: 149000,
      realTimeFactor: 0.051,
      chunksCount: 96,
      geminiRequestsCount: 1,
      measuredAt: Date.now() - 86400000 * 7,
    },
    topics: [
      {
        id: 'top_math_1',
        title: 'Definition of the Unilateral Laplace Transform & Region of Convergence',
        startTimestamp: '00:00',
        endTimestamp: '10:15',
        summary: 'Integral definition L{f(t)} = ∫[0,∞] e^(-st) f(t) dt, complex frequency s = σ + jω, and piecewise continuity.',
      },
      {
        id: 'top_math_2',
        title: 'Transforms of Elementary Standard Functions',
        startTimestamp: '10:16',
        endTimestamp: '19:40',
        summary: 'Derivations for constant 1, t^n, e^(at), sin(at), cos(at), sinh(at), and cosh(at).',
      },
      {
        id: 'top_math_3',
        title: 'Linearity and First Shifting (Frequency Shift) Theorem',
        startTimestamp: '19:41',
        endTimestamp: '28:50',
        summary: 'Theorem: L{e^(at) f(t)} = F(s - a) and dampening factor analysis in dynamic circuit analysis.',
      },
      {
        id: 'top_math_4',
        title: 'Laplace Transform of Derivatives and Integrals',
        startTimestamp: '28:51',
        endTimestamp: '38:20',
        summary: 'Transform of f\'(t) and f\'\'(t) incorporating initial boundary conditions f(0) and f\'(0).',
      },
      {
        id: 'top_math_5',
        title: 'Solving Initial Value Problems (IVPs) in RLC Circuits',
        startTimestamp: '38:21',
        endTimestamp: '48:00',
        summary: 'Converting continuous-time differential equations into algebraic equations in the s-domain and partial fraction inversion.',
      },
    ],
    summary: {
      tldr: 'An exploration of Laplace transforms from fundamental integral definitions and standard elemental formulas to frequency shifting, derivative operational theorems, and solving engineering differential equations.',
      keyPoints: [
        {
          point: 'Laplace Transform converts calculus into algebra',
          explanation: 'By mapping time-domain functions f(t) into complex frequency s-domain F(s), linear differential equations become simple algebraic polynomial equations.',
          evidenceTimestamp: '02:40',
        },
        {
          point: 'First Shifting Theorem scales exponential modulation',
          explanation: 'Multiplying a time-domain signal f(t) by e^(at) corresponds to shifting its s-domain transform by a: L{e^(at) f(t)} = F(s - a).',
          evidenceTimestamp: '21:15',
        },
        {
          point: 'Derivative Theorem naturally incorporates Initial Conditions',
          explanation: 'L{f\'(t)} = s F(s) - f(0) and L{f\'\'(t)} = s^2 F(s) - s f(0) - f\'(0). This is why engineers prefer Laplace over classical complementary function / particular integral methods.',
          evidenceTimestamp: '30:20',
        },
        {
          point: 'Region of Convergence (ROC) ensures integral convergence',
          explanation: 'The improper integral converges only when the real part of s is strictly greater than the exponential order α of the function: Re(s) > α.',
          evidenceTimestamp: '08:30',
        },
      ],
      formulas: [
        {
          name: 'Definition of Laplace Transform',
          formula: 'L{f(t)} = F(s) = ∫[0, ∞] e^(-st) f(t) dt',
          description: 'Integral transform kernel transforming time function f(t) for t >= 0 into s-domain.',
          evidenceTimestamp: '04:10',
        },
        {
          name: 'Transform of Exponential Function',
          formula: 'L{e^(at)} = 1 / (s - a), for s > a',
          description: 'Base exponential transform used in decaying circuit transient responses.',
          evidenceTimestamp: '13:20',
        },
        {
          name: 'Transforms of Sine and Cosine',
          formula: 'L{sin(at)} = a / (s^2 + a^2), L{cos(at)} = s / (s^2 + a^2)',
          description: 'Frequency domain representations for undamped sinusoidal oscillations.',
          evidenceTimestamp: '16:45',
        },
        {
          name: 'Second Derivative Transform',
          formula: 'L{f\'\'(t)} = s^2 F(s) - s f(0) - f\'(0)',
          description: 'Operational formula directly incorporating initial displacement f(0) and velocity f\'(0).',
          evidenceTimestamp: '32:40',
        },
      ],
      definitions: [
        {
          term: 'Laplace Transform',
          definition: 'An integral transform that maps a real-valued time-domain signal f(t) into a complex frequency-domain function F(s), where s = σ + jω.',
          evidenceTimestamp: '04:10',
        },
        {
          term: 'Exponential Order',
          definition: 'A function f(t) is of exponential order α if there exist constants M and T such that |f(t)| <= M * e^(αt) for all t > T.',
          evidenceTimestamp: '07:45',
        },
        {
          term: 'Partial Fraction Decomposition',
          definition: 'An algebraic technique used in inverse Laplace transformation to split a complex rational function F(s) = P(s)/Q(s) into simpler sum of terms with known standard inverses.',
          evidenceTimestamp: '42:15',
        },
      ],
    },
    flashcards: [
      {
        id: 'fc_math_1',
        question: 'What is the definition of the unilateral Laplace Transform L{f(t)}?',
        answer: 'F(s) = ∫ from 0 to ∞ of e^(-st) * f(t) dt, where s is a complex frequency parameter s = σ + jω.',
        sourceTimestamp: '04:10',
        difficulty: 'easy',
      },
      {
        id: 'fc_math_2',
        question: 'What is L{t^n} for a non-negative integer n?',
        answer: 'n! / s^(n+1), where s > 0.',
        sourceTimestamp: '12:15',
        difficulty: 'easy',
      },
      {
        id: 'fc_math_3',
        question: 'State the First Shifting Theorem (Frequency Shift).',
        answer: 'If L{f(t)} = F(s), then L{e^(at) * f(t)} = F(s - a).',
        sourceTimestamp: '21:15',
        difficulty: 'easy',
      },
      {
        id: 'fc_math_4',
        question: 'What is L{f\'(t)} in terms of F(s) and initial conditions?',
        answer: 'L{f\'(t)} = s * F(s) - f(0).',
        sourceTimestamp: '30:20',
        difficulty: 'easy',
      },
      {
        id: 'fc_math_5',
        question: 'What is L{e^(-3t) * cos(4t)} using the First Shifting Theorem?',
        answer: '(s + 3) / ((s + 3)^2 + 16).',
        sourceTimestamp: '24:30',
        difficulty: 'medium',
      },
      {
        id: 'fc_math_6',
        question: 'What conditions guarantee that the Laplace transform of f(t) exists?',
        answer: 'f(t) must be piecewise continuous on every finite interval [0, T] and must be of exponential order as t -> ∞.',
        sourceTimestamp: '07:45',
        difficulty: 'medium',
      },
      {
        id: 'fc_math_7',
        question: 'What is the Laplace transform of the unit step function u(t - a) for a >= 0?',
        answer: 'e^(-as) / s.',
        sourceTimestamp: '27:10',
        difficulty: 'medium',
      },
      {
        id: 'fc_math_8',
        question: 'How does Laplace transform simplify solving initial value differential equations compared to classical methods?',
        answer: 'It converts differential operators into algebraic multiplications by s and automatically incorporates initial conditions into the algebraic equation.',
        sourceTimestamp: '39:50',
        difficulty: 'medium',
      },
      {
        id: 'fc_math_9',
        question: 'What is L{sinh(at)}?',
        answer: 'a / (s^2 - a^2), for s > |a|.',
        sourceTimestamp: '18:20',
        difficulty: 'easy',
      },
      {
        id: 'fc_math_10',
        question: 'What is the Convolution Theorem for Laplace transforms?',
        answer: 'L{f(t) * g(t)} = F(s) * G(s), where * represents the convolution integral ∫[0, t] f(τ) g(t - τ) dτ.',
        sourceTimestamp: '45:30',
        difficulty: 'hard',
      },
    ],
    quiz: [
      {
        id: 'qz_math_1',
        question: 'What is the Laplace transform of f(t) = 1?',
        options: ['1', '1/s', 's', '1/s^2'],
        correctAnswer: '1/s',
        explanation: '∫[0,∞] e^(-st) dt = [-e^(-st)/s] from 0 to ∞ = 0 - (-1/s) = 1/s for Re(s) > 0.',
        sourceTimestamp: '10:50',
      },
      {
        id: 'qz_math_2',
        question: 'Find L{sin(3t)}.',
        options: ['3 / (s^2 + 9)', 's / (s^2 + 9)', '3 / (s^2 - 9)', 's / (s^2 - 9)'],
        correctAnswer: '3 / (s^2 + 9)',
        explanation: 'By standard formula, L{sin(at)} = a / (s^2 + a^2). For a = 3, this evaluates to 3 / (s^2 + 9).',
        sourceTimestamp: '16:45',
      },
      {
        id: 'qz_math_3',
        question: 'According to the first shifting theorem, what is L{e^(2t) * t^3}?',
        options: ['6 / (s - 2)^4', '6 / s^4', '3 / (s - 2)^3', '24 / (s - 2)^4'],
        correctAnswer: '6 / (s - 2)^4',
        explanation: 'L{t^3} = 3! / s^4 = 6 / s^4. Multiplying by e^(2t) shifts s -> (s - 2), yielding 6 / (s - 2)^4.',
        sourceTimestamp: '22:40',
      },
      {
        id: 'qz_math_4',
        question: 'Given y\'\' + 4y = 0 with y(0) = 1, y\'(0) = 0. Taking the Laplace transform yields which s-domain expression for Y(s)?',
        options: ['s / (s^2 + 4)', '2 / (s^2 + 4)', '1 / (s^2 + 4)', '(s + 1) / (s^2 + 4)'],
        correctAnswer: 's / (s^2 + 4)',
        explanation: 'L{y\'\'} = s^2 Y(s) - s y(0) - y\'(0) = s^2 Y(s) - s. So (s^2 + 4) Y(s) - s = 0 ⇒ Y(s) = s / (s^2 + 4). Inversion gives y(t) = cos(2t).',
        sourceTimestamp: '41:10',
      },
      {
        id: 'qz_math_5',
        question: 'What is the Laplace transform of the Dirac delta function δ(t - a)?',
        options: ['e^(-as)', '1/s', 'e^(as)/s', '0'],
        correctAnswer: 'e^(-as)',
        explanation: 'By the sifting property of the impulse function, ∫[0,∞] e^(-st) δ(t - a) dt = e^(-as).',
        sourceTimestamp: '28:15',
      },
      {
        id: 'qz_math_6',
        question: 'Which property of Laplace transform states: L{t * f(t)} = -d/ds [F(s)]?',
        options: [
          'Differentiation in frequency domain',
          'Integration in time domain',
          'Second Shifting Theorem',
          'Initial Value Theorem',
        ],
        correctAnswer: 'Differentiation in frequency domain',
        explanation: 'Multiplying by t in the time domain corresponds to differentiating with respect to s and negating in the frequency domain.',
        sourceTimestamp: '35:20',
      },
      {
        id: 'qz_math_7',
        question: 'What is the inverse Laplace transform L^(-1){ 1 / (s + 5) }?',
        options: ['e^(-5t)', 'e^(5t)', 'sin(5t)', '5t'],
        correctAnswer: 'e^(-5t)',
        explanation: 'Since L{e^(at)} = 1 / (s - a), setting a = -5 produces 1 / (s + 5), giving inverse e^(-5t).',
        sourceTimestamp: '13:20',
      },
      {
        id: 'qz_math_8',
        question: 'In electrical engineering, why is the Laplace variable s called complex frequency?',
        options: [
          'Because s = σ + jω combines damping rate σ and oscillation frequency ω',
          'Because it produces imaginary voltages',
          'Because it only applies to quantum circuits',
          'Because Fourier transform is non-convergent for all periodic waves',
        ],
        correctAnswer: 'Because s = σ + jω combines damping rate σ and oscillation frequency ω',
        explanation: 'The real part σ represents exponential attenuation or growth (envelope damping), while the imaginary part ω represents angular frequency in radians per second.',
        sourceTimestamp: '05:40',
      },
    ],
    groundedQA: [
      {
        id: 'sample_qa_math_1',
        question: 'Why do we need the Laplace transform instead of ordinary Fourier transform for engineering circuits?',
        answer: 'As explained by the professor, the Fourier transform integral often diverges for signals that do not decay to zero at infinity (such as step inputs, ramps, or growing exponentials). The Laplace transform introduces an exponential convergence factor e^(-σt) in s = σ + jω, allowing us to analyze unstable or transient systems. Furthermore, the unilateral Laplace transform natively incorporates initial energy storage conditions like capacitor voltages v(0) and inductor currents i(0).',
        confidence: 'high',
        citations: [
          {
            timestamp: '05:40',
            snippet: 's = σ + jω incorporates an attenuation envelope that forces integral convergence where pure Fourier transforms would diverge.',
            topic: 'Definition of the Unilateral Laplace Transform',
          },
          {
            timestamp: '30:20',
            snippet: 'L{f\'(t)} = s F(s) - f(0) accounts for non-zero initial conditions automatically.',
            topic: 'Laplace Transform of Derivatives',
          },
        ],
        createdAt: Date.now() - 3600000,
      },
    ],
    transcript: [
      {
        id: 'math_seg_1',
        start: 0,
        end: 50,
        startTimestamp: '00:00',
        endTimestamp: '00:50',
        text: 'Good afternoon. Today we study the Laplace transform, one of the most powerful mathematical tools ever invented for electrical engineers, mechanical control systems, and applied mathematics.',
      },
      {
        id: 'math_seg_2',
        start: 50,
        end: 160,
        startTimestamp: '00:50',
        endTimestamp: '02:40',
        text: 'Why do engineers love Laplace transforms? Because solving linear differential equations with classical calculus is tedious. Laplace transforms convert differential equations into simple high school algebra. Derivatives turn into multiplications by s, and integrals turn into divisions by s.',
      },
      {
        id: 'math_seg_3',
        start: 160,
        end: 340,
        startTimestamp: '02:40',
        endTimestamp: '05:40',
        text: 'Here is the formal unilateral definition: L{f(t)} = F(s) = the integral from 0 to infinity of e to the power minus s t times f(t) dt. Here s is a complex variable, equal to sigma plus j omega.',
      },
      {
        id: 'math_seg_4',
        start: 340,
        end: 550,
        startTimestamp: '05:40',
        endTimestamp: '09:10',
        text: 'Notice that the integral is evaluated only for t greater than or equal to zero. That is why it is called the unilateral or one-sided Laplace transform. For the integral to converge, the function f(t) must be piecewise continuous and of exponential order.',
      },
      {
        id: 'math_seg_5',
        start: 550,
        end: 780,
        startTimestamp: '09:10',
        endTimestamp: '13:00',
        text: 'Let us derive the standard elementary transforms: for f(t) = 1, the transform is 1/s. For f(t) = t^n, the transform is n! / s^(n+1). For e^(at), the integral gives 1 / (s - a).',
      },
      {
        id: 'math_seg_6',
        start: 1180,
        end: 1440,
        startTimestamp: '19:40',
        endTimestamp: '24:00',
        text: 'Now consider the First Shifting Theorem: if you multiply any function f(t) by e^(at), its Laplace transform simply replaces s with s - a. For example, L{e^(at) cos(bt)} is (s - a) / ((s - a)^2 + b^2).',
      },
      {
        id: 'math_seg_7',
        start: 1730,
        end: 2020,
        startTimestamp: '28:50',
        endTimestamp: '33:40',
        text: 'The most important theorem for differential equations is the transform of derivatives: L{f\'(t)} = s F(s) - f(0). For the second derivative, L{f\'\'(t)} = s^2 F(s) - s f(0) - f\'(0). Look at that: initial conditions are directly built into the equation!',
      },
      {
        id: 'math_seg_8',
        start: 2300,
        end: 2600,
        startTimestamp: '38:20',
        endTimestamp: '43:20',
        text: 'When we solve an RLC circuit like L d^2i/dt^2 + R di/dt + (1/C) i = V(t), we apply Laplace transforms to both sides, isolate I(s), expand using partial fractions, and take the inverse Laplace transform. That yields the complete response without separate particular solutions.',
      },
    ],
  },
];
